### ISSUE TITLE
Going back pages to quickly in MA3 will crash Media Portal

### ISSUE THREAD

**Issue by xsystematic** [japanesemediamanager/MyAnime3#23] opened 2015-01-22 15:47 UTC
This also happened in previous versions of My Anime 3. It may be a media portal bug but I can only reproduce the bug with MA3.

If you go back several pages in MA3 to the Media Portal home screen to quickly Media Portal will crash when you try to load MA3 again.
![untitled](https://cloud.githubusercontent.com/assets/10373766/5858683/f47813c8-a24c-11e4-81e3-8187aa5acbac.png)
Here are my log files from Media Portal and My Anime 3, I have also included a zip file from Watch Dog (part of media portal) with all the logs from the crash
https://www.dropbox.com/sh/wrtomombl338hxo/AABLZznjKeRK__EU-j4-qE0Ra?dl=0

**Comment by RickDB** [comment] 2016-09-06 20:58
Tested here and can't reproduce this one anymore (had it as well), @xsystematic are you able still able to crash it with quick back navigation?

**Comment by ElementalCrisis** [comment] 2016-09-08 10:50
Fixed in 3.6.0.10.

**Closed by ElementalCrisis** 2016-09-08 10:50 UTC
Labels: Bug - High Priority
